### ISSUE TITLE
Fix Current Year value in footer

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/news-website#11]
![image](https://github.com/user-attachments/assets/213c8e0b-532b-41d7-a3e2-e92de487790f)

**Comment by RajatX24** [comment]
hello @imhardikdesai ,

I would like to work on this, please assign it to me.

**Comment by imhardikdesai** [comment]
@RajatX24 make sure it has dynamic values, so for example if the current year is 2026, it shows correct value over the time

> Note: use javascript's Date object

**Comment by RajatX24** [comment]
hello @imhardikdesai ,

I have made fixed the bug and made a PR for the same.
You can check it out here: https://github.com/imhardikdesai/news-website/pull/14
