### ISSUE TITLE
Issue: Dark mode not implemented in category dropdown list

### ISSUE THREAD

**Issue by NamanSriva** [imhardikdesai/news-website#18]
Description : While switching to dark mode the items in category dropdown have white background.
 #13 

![Screenshot (104)](https://github.com/user-attachments/assets/1d44ed5b-96e2-4c61-b578-7f085961899d)

Steps to reproduce - 
1) Open the website 
2) On the navbar click category dropdown
3) A list appears 

Suggestion: In dark mode the background should be black and texts should be white for proper dark mode UI.

**Comment by imhardikdesai** [comment]
@NamanSriva please start working on it!!

**Comment by NamanSriva** [comment]
@imhardikdesai created a PR for same, you can check.
