### ISSUE TITLE
Create Proper Card Gallery for news

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/news-website#4]
### Description

Create Proper Card Gallery for news

### Scope

- ![image](https://github.com/imhardikdesai/news-website/assets/87645745/942fe871-af85-4ae8-b804-e2ac1119235d)
- Card Grid should be proper 
- Fix CSS layout issue

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- CSS
- Responsive Design
- Hacktoberfest

**Comment by mukulpythondev** [comment]
I want to work on this issue please assigned to me

**Comment by imhardikdesai** [comment]
@mukulpythondev , Sure You can start working on it

**Comment by Abishkardhenga** [comment]
@imhardikdesai hey brother I have created pull request for this issue hope You see and Merge it and Give me a feedback for my work

**Comment by Abishkardhenga** [comment]
@imhardikdesai  please accept and merge my PR

**Comment by imhardikdesai** [comment]
@Aabiskar-dhenga You did a great job. Thanks for your contributions. I will merge your PR.
