### ISSUE TITLE
Implement Dark Mode 

### ISSUE THREAD

**Issue by Chayandev** [imhardikdesai/news-website#6]
I want to implement Dark mode and also smooth transition from light to dark mode and vice versa.

@imhardikdesai  please assign me this .

**Comment by imhardikdesai** [comment]
Hello @Chayandev , Please start working on issue i have assigned you

**Comment by Chayandev** [comment]
Sure

**Comment by Abishkardhenga** [comment]
can you assign this issue to me

**Comment by imhardikdesai** [comment]
#7
